# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0054_auto_20170119_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtask',
            options={'ordering': ('parent_pos', 'time_started')},
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='processstep',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='processstep_pos',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='status',
        ),
        migrations.AddField(
            model_name='processtask',
            name='_status',
            field=models.CharField(choices=[(b'RECEIVED', b'RECEIVED'), (b'RETRY', b'RETRY'), (b'REVOKED', b'REVOKED'), (b'SUCCESS', b'SUCCESS'), (b'STARTED', b'STARTED'), (b'FAILURE', b'FAILURE'), (b'PENDING', b'PENDING')], db_column='status', default=b'PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='processtask',
            name='parallel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processtask',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='WorkflowEngine.ProcessTask'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='parent_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processtask',
            name='step',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='retried',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retried_task', to='WorkflowEngine.ProcessTask'),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='undone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_task', to='WorkflowEngine.ProcessTask'),
        ),
    ]
