# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0055_remove_processtask_celery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('STARTED', 'STARTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
